### ISSUE TITLE
build faild by openssl 1.1

### ISSUE THREAD

**Issue by zssazrael** [Wind4/vlmcsd#14]
crypto_openssl.c: In function 'Sha256HmacInit_OpenSSL':
crypto_openssl.c:18:2: warning: implicit declaration of function 'HMAC_CTX_init'; did you mean 'HMAC_CTX_new'? [-Wimplicit-function-declaration]
  HMAC_CTX_init(c);
  ^~~~~~~~~~~~~
  HMAC_CTX_new
crypto_openssl.c: In function 'Sha256HmacFinish_OpenSSL':
crypto_openssl.c:36:2: warning: implicit declaration of function 'HMAC_CTX_cleanup'; did you mean 'HMAC_CTX_get_md'? [-Wimplicit-function-declaration]
  HMAC_CTX_cleanup(c);
  ^~~~~~~~~~~~~~~~
  HMAC_CTX_get_md
crypto_openssl.c: In function 'Sha256Hmac':
crypto_openssl.c:42:11: error: storage size of 'Ctx' isn't known
  HMAC_CTX Ctx;
           ^~~
crypto_openssl.c:42:11: warning: unused variable 'Ctx' [-Wunused-variable]
crypto_openssl.c:59:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [../build/crypto_openssl.o] Error 1
make: *** [vlmcsd] Error 2

**Comment by rouben** [comment]
That's probably due to the explanation [https://github.com/Wind4/vlmcsd/blob/master/README.openssl](in the OpenSSL readme). What build script are you using? What platform?

**Comment by rouben** [comment]
Given that using OpenSSL rather than built-in crypto implementation is an operational requirement for this software, I am closing this issue. According to the author, OpenSSL support is experimental. Maybe in future releases more solid OpenSSL support would be introduced, but for the time being, this is a "won't fix" issue, I'm afraid.
