### ISSUE TITLE
"0x8007000D The data is invalid" when activating

### ISSUE THREAD

**Issue by smaitlx1** [Wind4/vlmcsd#6]
Error message and log file attached.
![image](https://cloud.githubusercontent.com/assets/26071698/23378505/f27daf5c-fcf8-11e6-8c82-3d9e11941e00.png)

![image](https://cloud.githubusercontent.com/assets/26071698/23378594/51c038ae-fcf9-11e6-9c04-3a1a46c90e20.png)

**Comment by Wind4** [comment]
[Error code 0x8007000D when trying to activate a Windows server 2008 or Windows 7 machine using any type of product key.](https://support.microsoft.com/en-us/help/2230957/)

**Comment by smaitlx1** [comment]
That key already has Full Control granted to SYSTEM.

**Comment by Wind4** [comment]
Long time no response

**Comment by rouben** [comment]
I can confirm this bug on Windows builds. Linux builds appear to be OK...

**Comment by ChlorideCull** [comment]
All of them or some of them? [Some executables are being incorrectly flagged as trojans](https://www.virustotal.com/en/file/d8910723a2c619941f71f97b50efd5bb302914cc51db2e3721ee804be05a3ba6/analysis/) by some anti-viruses, so make sure you don't have one running that's interfering with it.

Other than that, I could try reproducing and fixing it, if you could give me details on environment:

- Information on the Windows install it's running on, as well as the Windows install it's trying to activate
  - Version (7, 8, 8.1, 10, Server 2016?)
  - Language
  - Fully updated?
- "Official" or your own build?

**Comment by smaitlx1** [comment]
I've observed it on Windows 10 64-bit and Windows Server 2016, but it only seems to occur if it's running on the same machine being activated.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by rouben** [comment]
Ditto. Mine was Windows 10 64-bit Pro, and I was trying to make it "self-activating". Tried multiple official builds, including [latest svn1108](https://github.com/Wind4/vlmcsd/releases/latest). The flavour of the executable (GCC vs. native vs. RPC) didn't make a difference and yielded the same result.

Anti-virus/anti-malware was not triggered, and the vlmcsd daemon showed a successful connection, request and response to the activation request on the console log.

#### Steps to reproduce:
1. Deploy **vlmcsd** either as a Windows service, or just run it in daemon mode on the command line on the machine you want to activate.
2. Make sure to allow network access when prompted by Windows.
3. Set up **slmgr.vbs** to talk to localhost, as such `slmgr.vbs /skms localhost`
4. Attempt activation using **slmgr.vbs** like so `slmgr.vbs /ato`

Please note that the above works fine when SSH tunnels are used. In other words, if I use PuTTY or any other SSH client on Windows, to set up an SSH tunnel from localhost TCP port 1688 to the KMS host on another network, and use the above commands to activate and configure **slmgr.vbs**, then it does work...

My next steps to try would be to run the vlmcsd daemon on a Windows machine, and have another Windows machine activate against it. If this fails too, I would be inclined to think that there's something generally broken with the Windows builds, since it would eliminate the possibility that the activation fails due to the vlmcsd daemon running on the same physical host as the client...

**Comment by smaitlx1** [comment]
I can confirm Windowa builds work as expected when activating any machine othet than the one the daemon is running on.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by ChlorideCull** [comment]
Ah, then the answer is simple, since Windows 8.1 (I think, might be 8) KMS activation on localhost has been disabled, since it's impossible to encounter on a legitimate setup - a KMS server cannot activate itself.

You can install TeamViewer and assign two IPs to the VPN network adapter to circumvent it, or run the host in a VM from the floppy image. Check the man page for that.

**Comment by jeffery9** [comment]
try to active office 2016, the same issue/
![image](https://user-images.githubusercontent.com/1404460/49682197-4663bc00-faeb-11e8-9e76-5140e30893a9.png)

**Comment by Zibri** [comment]
why is this closed?

**Comment by rouben** [comment]
@Zibri this issue is closed, because it's not a bug or problem with vlmcsd. The reason for this error in this case is because the KMS server and the KMS client (Windows/Office) that's being activated are on the same machine using "localhost" or "127.0.0.1" as the KMS server. This is not supported by Microsoft and there is nothing that can be done to "fix" this on the vlmcsd end.

If you're seeing this error, and you are using a virtual network adapter (either VPN or TeamViewer) to circumvent this limitation, or if your vlmcsd server is running on a different machine or VM, please submit a new bug report with all the pertinent details, like IP addresses of the vlmcsd server and the machine trying to get activated.

**Comment by Zibri** [comment]
my bad.. I solved it in 2 different ways... thanks!

**Comment by smaitlx** [comment]
To help others who encounter this, two additional ways around it:
Create a NAT rule on your router that forwards port 1688 TCP back to your server.
My solution: Use a free load balancer (HAProxy for people who like Linux or Kemp has a free edition as well) and load balance port 1688 TCP through a VIP on the load balancer.

**Comment by Zibri** [comment]
> To help others who encounter this, two additional ways around it:

My solutions are:

1) install vlmcsd on my wifi router :D 
2) use a tap interface as suggested in vlmcsd manual and run it on localhost
