### ISSUE TITLE
Aren't there any plans to update vlmcsd.kmd?

### ISSUE THREAD

**Issue by arbv** [Wind4/vlmcsd#75]
While the implementation seems to work fine, the included `vlmcsd.kmd` file is outdated. Are there any plans to update it?

**Comment by Mr-Precise** [comment]
How to edit it
I didn't find any tool to edit this file 🤔

**Comment by arbv** [comment]
> How to edit it
> I didn't find any tool to edit this file 🤔
> 

I wish I could help.

**Comment by rouben** [comment]
Given that KMD files do not affect functionality, other than what goes in the log files (activations still work), we don't usually update it. The other reason why we don't do it, is because we'd like to keep the code on here as close as possible to the upstream.

Having said this, the original author of this tool, built a Windows-only program called "License Manager" which is able to update the KMD file. The tool can be downloaded [here](https://forums.mydigitallife.net/threads/miscellaneous-kms-related-developments.52594/page-44#post-1736669) - note, registration is required to access this page.
