### ISSUE TITLE
I see no project's license

### ISSUE THREAD

**Issue by sskras** [Wind4/vlmcsd#8]
Either there is no license declared, or it's hidden quite deep somewhere in the repository.

**Comment by Wind4** [comment]
This repository only mirror MDL fourm. you can see [here](https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/).

**Comment by sskras** [comment]
I am required to have an account on MDL to see the content.
Have your code a license assigned?

**Comment by rouben** [comment]
I'm in contact with the original code author in hopes to ask what license they prefer. As a rule of thumb, however, a lack of license can be generally interpreted as follows: https://choosealicense.com/no-license/

Given the nature of this code, however, I think the author's intentions are more closer aligned with the "public domain", as in the [unlicense](https://choosealicense.com/licenses/unlicense/).

**Comment by Noiwex** [comment]
What's your problem?

**Comment by rouben** [comment]
I don’t want to speak on @sskras behalf, but I think without a license this code automatically becomes “all rights reserved” which is quite restrictive. It would be nice to have a definitive response from the author...

As per my last note, I’ve tried reaching out to the author, but they are ignoring me, I think. :(

**Comment by rouben** [comment]
Based on my research of licensing, and the author’s lack of response, I think it’s safe to assume this software is “all rights reserved” and not “open source”.

**Comment by sskras** [comment]
@Noiwex , excuse me please for a late response:

> What's your problem?

I am having difficulty understanding a relationships of the project's code to the outer world:

* in what differently licensed projects could I incorporate this (untouched) code legally?
* are against private modifications of the code?
* do you accept code contributions from other people?
* does all the code come from your original work (or maybe is something copied from differenly licensed / restricted sources)?

Just a bit of clarity on what do you allow / what do you restrict about it.

As @rouben pointed nicely to no-license article, I thought the author's idea was to put the code into so-called Public Domain.

Can our primary guess be right that the code is dedicated to public domain?

**Comment by Noiwex** [comment]
It's essentially a crack for microsoft products, how are you going to enforce copyright on it lmao.

**Comment by sskras** [comment]
That are two different things: requirements for handling the code + functionality the code implements.

**Comment by sskras** [comment]
These are two different things: requirements for handling the code + functionality the code implements.
I am not going to enforce anything for anyone.  

Just asking the authors to write down their point of view (with regard to code modifications / reuse:)

BTW, even if it should prove illegal to use the binaries, creating them for investigation could perfectly be legally acceptable (depends on the state's law of copyright and IP).

Hence the question.  Public domain would do.
Of course, if disassembling the original binaries was used, things get tougher.

**Comment by rouben** [comment]
I managed to actually get a response from the code's author, Hotbird64 on the MDL forums. The closest I'd really gotten to getting a straight, explicit answer, is [this post](https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/page-75#post-1481404) and [this one](https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/page-74#post-1479763).

In summary, here are my findings:
- The author doesn't feel they can grant anyone a license to the code. This implies a default proprietary "all rights reserved" license.
- The author implicitly indicated that: compiling the code and using either the author-supplied or self-compiled binaries is OK.
- The author explicitly states that "source code is available", however, there is no explicit license provided.
- The author explicitly states that mirroring of the (source code and binaries) is against their wishes in [this post](https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/page-75#post-1480976)
- Questions re: contribution and inclusion in other projects were not specifically answered, although there are a number of derivatives and distributions built by others on the MDL forums available. For example [this one](https://forums.mydigitallife.net/threads/miscellaneous-kms-related-developments.52594/page-33#post-1475544).

I'd tried, on numerous occasions to probe further and encourage the author to just pick a license, but to not avail. For the reasons above, I can no longer participate in this project as a contributor, even though I would love to.

If I had to guess, I think the author just doesn't want his code and his work publicly available and "out in the open"; there's a lot of paranoia prevalent in that community. I personally think that the "shielding" provided by the MDL forum mandatory registration wall "against Microsoft's army of copyright/anti-piracy enforcers" is nonsense, but alas, that is merely my opinion.

In summary, given the author's wishes, I think the ethical thing to do is take down this mirror of the code and request that all forks thereof, and other mirrors be taken down as well. Since this is not my GitHub project, I am tagging @Wind4 in this post, looking for his response/analysis of what has transpired. If anyone else can offer any other feedback, please let me know.

**Comment by Noiwex** [comment]
Are you Microsoft troll?

**Comment by lifehome** [comment]
Can we close this? It's not even an "issue" to the codebase itself, given the author explicitly stated not to license the code. In addition there aren't such thing of mandatory policy on licensing a software, and if someone is having issue on their use or redistribution then just redesign it in clean room.

**Comment by sskras** [comment]
@lifehome , of course it's not an issue, it's meta-issue!  Where else do you prefer to discuss it: MDL forum ?

> there aren't such thing of mandatory policy on licensing a software, 

I guess you didn't know _GitHub Terms of Service_, namely [5. License Grant to Other Users](https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users):

> > If you set your pages and repositories to be viewed publicly, **you grant each User** of GitHub a nonexclusive, worldwide **license to use, display, and perform** Your Content through the GitHub Service and **to reproduce Your Content** solely on GitHub as permitted through GitHub's functionality (for example, through forking). _**You may grant further rights**_ if you adopt a license.

I read this as a requirement for a hosted code to be open source software.  What do others think?

In such case, if the code is not open source, you violate _GitHub Terms of Service_, and the repository should be taken down.  Which would be sad, but correct to do.  So I agree with @rouben:

> I think the ethical thing to do is take down this mirror of the code and request that all forks thereof, and other mirrors be taken down as well.

@lifehome:

> and if someone is having issue on their use or redistribution then just redesign it in clean room.

That one is interesting.  Do you know this code to be designed in a not clean room way, or do you only guess that?

**Comment by rouben** [comment]
Agree with @sskras. I think the right thing to do given the circumstances is to take down the mirrors of source and binaries (I’ll leave that up to @Wind4 as this is not my repo and project). Having said this, there’s nothing stopping us from supporting and “promoting” vlmcsd on github. So we could proceed as follows:
1. Delete all releases
2. Delete git repo
3. Keep support tracker (issues)

Alternatively if anyone else wants to take a crack at convincing the author (Hotbird64) to release this code as open source or public domain, please feel free.

Having said that, given the code quality, I’d much rather rewrite the thing, preferably with Hotbird64’s permission/blessing. A complete rewrite would technically be free of the restrictions placed on the code by the author out of fear.

**Comment by rouben** [comment]
I don't think this will ever get resolved. If anyone is willing to try and convince the author to release this code under an open source or even public domain license, please feel free to do so [upstream](https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/). Note: registration is required to access the site linked.
