### ISSUE TITLE
How add gvlk key for Windows 11 PRO

### ISSUE THREAD

**Issue by DFITSupport** [Wind4/vlmcsd#81]
Hello, how to add gvlk key for Windows 11 PRO to vlmcsd kms server ?

**Comment by DFITSupport** [comment]
Not really. The newly installed Windows 10/11 pro is not activated, if you explicitly specify the windows 10/11 corporate product key, then it is activated successfully.
All other versions of Windows activate successfully.

Windows 11 Pro Windows 10 Pro | W269N-WFGWX-YVC9B-4J6C9-T83GX - not Activated
Windows 11 Enterprise Windows 10 Enterprise | NPPR9-FWDCX-D2C8J-H872K-2YT43   Activated by kms server

**Comment by rouben** [comment]
Did you try the step-by-step commands listed on [https://wind4.github.io/vlmcsd](the website), or are you just using the GUI? The example on that page is actually for Windows 10/11 Pro.  Note that if you're upgrading Home to Pro, you may need to try the Enterprise key first in the GUI to trigger an update of the Windows edition, then switch to a Pro key. That process is a bit janky, at least for me (Windows issue, not related to vlmcsd). Also, obviously, please replace the KMS server with your own, rather than using the one in the example.

If you still can't get it to work, please provide the output of **slmgr.vbs -ato**. Ideally please paste it into a gist or pastebin rather than a screenshot, so any error codes and text are in text format. Also please include the vlmcsd log or console output as text. Is vlmcsd receiving the activation request from your Windows 11 Pro box?

**Comment by DFITSupport** [comment]
I'm sorry, this is my lack of attention. Windows did not activate because any product key was missing from the system. When indicated it - kms successfully activated the product. Thank you
