### ISSUE TITLE
Active Office 365 App Offline

### ISSUE THREAD

**Issue by vincentng190** [Wind4/vlmcsd#85]
Hello, how can I active Office 365 App offline? Or how to add key Office 365 to server data?
Thanks.

**Comment by rouben** [comment]
You can't; Office365 doesn't use KMS. You can download and activate Office LTSC, however, but you will not get the same features.

**Comment by thirdwheel** [comment]
> You can't; Office365 doesn't use KMS. You can download and activate Office LTSC, however, but you will not get the same features.

That's not entirely true. The Office365 C2R installer sometimes downloads the files required to change it from 365 to KMS (though the loss of certain features is likely if they rely on 365, and it may not be LTSC). There are guides online on how to do this and they can be found at your nearest Google.

**Comment by rouben** [comment]
TIL! 
Is this a supported operation? And is the reverse possible (converting LTSC to full CNR/O365)? Follow-up question: are features added/removed as appropriate to the specific build? For example, changing the Windows product key from Home to Enterprise download and enables Enterprise features. Does the same happen with Office when LTSC is converted to CNR/O365 and vice versa? I ask, because AFAIK, at least with Office 2016, KMS and non-KMS/retail versions were different builds/binaries.

**Comment by thirdwheel** [comment]
@rouben All very good questions. I haven't delved too deeply into this myself, I only know because we had a laptop come with the 365 stuff already installed and I stumbled on a method to convert it so it would use KMS, thus saving us the time consuming process of uninstalling 365 for the volume-licensing version.

**Comment by vincentng190** [comment]
Hi @thirdwheel, please tell me how to convert Office 365 to active with KMS. Office 365 you mention is Bussiness, ProPlus, or Enterprise?
