### ISSUE TITLE
能否介绍一下文件命名都什么意思？

### ISSUE THREAD

**Issue by fuwuqi298** [Wind4/vlmcsd#92]
能否介绍一下文件命名都什么意思？不知道用哪个。方便的话 windows  Linux 的命名都介绍一下，提前致谢！
![image](https://github.com/Wind4/vlmcsd/assets/169219922/269a9776-1f2a-4d95-82d2-93c7b0860630)

遇到问题：在 server 2012 R2 本地用 vlmcsd-Windows-x64.exe 做服务，server 2012 R2 激活不了，但用网上的 kms.03k.org 可以激活 server 2012 R2。
![image](https://github.com/Wind4/vlmcsd/assets/169219922/c73b0955-c961-4fd9-931c-11c6bb3a3462)

**Comment by thirdwheel** [comment]
Translation:
Can you tell me what the file naming means? Don't know which one to use
(first image)
Encountered a problem: When using vlmcsd-Windows-x64.exe to serve locally on server 2012 R2, server 2012 R2 cannot be activated, but server 2012 R2 can be activated using [kms.03k.org](http://kms.03k.org/) on the Internet.
(second image)

------

You can't serve locally. Windows will block any local access to a local KMS server, it must be served on a separate machine. I believe you can get around this with TAP adapters, but I've never tried this myself.

**Comment by thirdwheel** [comment]
See: https://github.com/Wind4/vlmcsd/issues/16

**Comment by fuwuqi298** [comment]
> See: #16
“Windows will block any local access to a local KMS server”
Thank you. Now I understand the question.

**Comment by fuwuqi298** [comment]
@thirdwheel Can you tell me what the file naming means?
![image](https://github.com/user-attachments/assets/a35ded30-9bdb-4c8f-b53a-588aaa4403b1)

**Comment by rouben** [comment]
* `vlmcs` - client, not KMS server. Useful for testing KMS servers.
* `vlmcsd` - KMS server
* `vlmcsdmulti` - universal (server or client, depending on what it's named). On Linux, the you can create a symbolic link to a vlmcsdmulti executable and depending on what the link is called, the executable will behave either as a KMS server or client. On Windows, I haven't tried this, but my guess is you will need to rename the file, because Windows doesn't really have symlinks that work the same way.
* `gcc, msrpc, etc` - different builds of the same program; is plain x86 or x64 works, just use that. On some Windows versions (like embedded or minimal) the regular versions don't work, because the DLLs the regular version needs are missing, so this is where the other builds can work, like gcc.

I hope this answers your question about names, @fuwuqi298. If you have no other questions, I'll close this issue. Let me know, please.

**Comment by fuwuqi298** [comment]
> * `vlmcs` - client, not KMS server. Useful for testing KMS servers.
> * `vlmcsd` - KMS server
> * `vlmcsdmulti` - universal (server or client, depending on what it's named). On Linux, the you can create a symbolic link to a vlmcsdmulti executable and depending on what the link is called, the executable will behave either as a KMS server or client. On Windows, I haven't tried this, but my guess is you will need to rename the file, because Windows doesn't really have symlinks that work the same way.
> * `gcc, msrpc, etc` - different builds of the same program; is plain x86 or x64 works, just use that. On some Windows versions (like embedded or minimal) the regular versions don't work, because the DLLs the regular version needs are missing, so this is where the other builds can work, like gcc.
> 
> I hope this answers your question about names, @fuwuqi298. If you have no other questions, I'll close this issue. Let me know, please.

thanks a lot👍
